https://towardsdatascience.com/introducing-numpy-part-1-understanding-arrays-3f6fecc97e3d/

### I do not understand strides

In [3]:
import sys
sys.executable

'/usr/local/opt/python@3.13/bin/python3.13'

In [3]:
%pip install numpy


Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

arr = np.array([[0, 1, 2],
                [3, 4, 5]])

arr


array([[0, 1, 2],
       [3, 4, 5]])

In [3]:
print(arr)

[[0 1 2]
 [3 4 5]]


In [46]:
arr.strides

(4,)

__Think of it as ↓__

row 0:  0  1  2
row 1:  3  4  5
          ↑
        element 2

__Select element 2 ↓__


Get the element at row 0, column 2 ↓

In [4]:
arr[0, 2]


np.int64(2)

or

Get the element at row 0, column 2 ↓

In [5]:
arr[0][2]


np.int64(2)

> In NumPy: first index = row, second index = column

__1D Array__(One Dimensional Array)

In [8]:
arr_1d = np.array([5, 4, 9])

In [47]:
arr_1d.strides

(8,)

In [9]:
print(arr_1d)

[5 4 9]


__2D Array__(Two Dimensional Array)

In [11]:
 arr_2d = np.array([[4.1, 2.0, 6.7],
                    [0.3, 9.4, 2.2]])

In [12]:
print(arr_2d)

[[4.1 2.  6.7]
 [0.3 9.4 2.2]]


__Tesor__ (An array with 3 or more dimensions)

In [41]:
arr_3d = np.array([[[1, 0, 1, 1],
                    [0, 1, 1, 1],
                    [1, 1, 0, 1]],
                     
                   [[0, 0, 0, 0],
                    [0, 0, 0, 0],
                    [1, 1, 0, 1]]])


In [14]:
print(arr_3d)

[[[1 0 1 1]
  [0 1 1 1]
  [1 1 0 1]]

 [[0 0 0 0]
  [0 0 0 0]
  [1 1 0 1]]]


In [10]:
print(arr_3d.shape)

(2, 3, 4)


* There are 2 tables (axis 0) or two stacked matrices

* Each table has 3 rows (axis 1)

* Each row has 4 elements (axis 2)

or

* Axis 0 (first number) → 2 → the outermost “blocks” (think of 2 big layers) 

* Axis 1 (second number) → 3 → the rows inside each block

* Axis 2 (third number) → 4 → the columns inside each row (or “elements in each

In [45]:
arr_3d.strides

(96, 32, 8)

__NumPy ndarrays have a fixed size at creation and can’t grow like a Python list or tuple.__ 

__Changing the size of an ndarray creates a new array and deletes the original.__

## __`Creating Arrays`__

[Complete listing of creation functions](https://numpy.org/doc/stable/reference/routines.array-creation.html)


![Python logo](https://towardsdatascience.com/wp-content/uploads/2024/09/1jOSQjRZvf9oSaD0C0IZgZg.png)

In [15]:
arrA = np.array([[10, 11, 12],
                [13, 14, 15]])

__NumPy arrays must be homogeneous (all elements same type).__

### __`Data Types`__

Arrays must contain data of the same type

functions infer the most suitable dtype or you can provide the dtype explicitly as an additional argument.

[Full List of Supported Data Types](https://numpy.org/doc/stable/user/basics.types.html)

![Python logo](https://towardsdatascience.com/wp-content/uploads/2024/09/1lX1v7yKr6K3I4KuqUz2X3A.png)


For string and Unicode dtypes, the length of the longest string or Unicode object must be included in the dtype argument

### __`array()`__

Create an array by passing the NumPy `array()` function a sequence, such as a list, which is then converted into an ndarray

In [17]:
import numpy as np

arr1d = np.array([1, 2, 3, 4])

type(arr1d)


print(type(arr1d))
print(arr1d)


<class 'numpy.ndarray'>
[1 2 3 4]


__Create an `ndarray` by passing the `array()` function a variable:__

In [18]:
my_sequence = [1, 2, 3, 4]

arr1d = np.array(my_sequence)

print(my_sequence)

[1, 2, 3, 4]


__To create a <u>multidimensional array</u>, pass `array()` a nested sequence, where each nested sequence is the same length.__

In [19]:
arr2d = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])

print(arr2d)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


__array’s attributes:__

In [21]:
arr2d.shape

(3, 3)

build an array from tuples

NumPy doesn’t care that they’re tuples. It treats them like lists.

In [23]:
import numpy as np

t = (1, 2, 3, 4)
arr = np.array(t)

print(arr)
print(type(arr))


[1 2 3 4]
<class 'numpy.ndarray'>


__arrays dimensions:__

In [24]:
print(arr2d)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [12]:
arr2d.ndim

2

__arrays strides__

how many bytes you have to skip in memory to move to the next element along each axis of an array. It tells NumPy how the array is laid out in memory.

In [ ]:
arr2d.strides

In [25]:
print(arr2d.strides)

(24, 8)


Strides = memory step size

In [28]:
import numpy as np

arry = np.array([10, 20, 30, 40], dtype=np.int32)


Saved in memory like this: 
| 10 | 20 | 30 | 40 |

Each int32 = 4 bytes

In [32]:
arry.strides



(4,)

To move from one element to the next → move 4 bytes

1D array → only one axis (axis 0)

Each element = 4 bytes

To move to the next element → move 4 bytes

| Axis   | Meaning |
| ------ | ------- |
| axis 0 | rows    |
| axis 1 | columns |


Strides are listed as:

(row stride, column stride)



In [37]:
arry2 = np.array([
    [1, 2, 3],
    [4, 5, 6]
], dtype=np.int32)


In [38]:
arry2.shape
# (2, 3)


(2, 3)

Row 0 → 1  2  3

Row 1 → 4  5  6


In [39]:
arry2.strides


(12, 4)

| Axis | Meaning             | Bytes    |
| ---- | ------------------- | -------- |
| 0    | Move down 1 row     | 12 bytes |
| 1    | Move right 1 column | 4 bytes  |


1 row = 3 elements × 4 bytes = 12 bytes

1 column = 1 element × 4 bytes = 4 bytes

___

In [9]:
arr_tuple_d = np.array(((0, 1, 2), (3, 4, 5), (6, 7, 8)))

print(arr_tuple_d)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


__Items in a NumPy array must share a single data type. You can mix sequence types like lists and tuples when creating an array, as long as their shapes are consistent.__

In [14]:
mixed_input = np.array([[0, 1, 2], (3, 4, 5), [6, 7, 8]])

print(mixed_input)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


This worked because NumPy reads the data type of the elements in a sequence rather than the data type of the sequence itself.

__`Jagged arrays` (rows of different lengths): Must use dtype='object', but it behaves more like a Python list of lists.__

In [17]:
arr2dee = np.array([[0, 1, 2], [3, 4, 5], [6, 7]], dtype='object') 

In [18]:
print(arr2dee)

[list([0, 1, 2]) list([3, 4, 5]) list([6, 7])]


In [19]:
print(arr2dee)
print(arr2dee.shape)
print(arr2dee.dtype)

[list([0, 1, 2]) list([3, 4, 5]) list([6, 7])]
(3,)
object


__3D array__
function a list containing two nested lists that each contained two nested lists. 

In [23]:
arr3d = np.array([[[0, 0, 0],
                   [1, 1, 1]],
                  [[2, 2, 2],
                   [3, 3, 3]]])

In [24]:
print(arr3d)


[[[0 0 0]
  [1 1 1]]

 [[2 2 2]
  [3 3 3]]]


### __`arange()`__
makes an array of integers

In [25]:
arr1d = np.arange(10)

In [26]:
print(arr1d)

[0 1 2 3 4 5 6 7 8 9]


__`step`__
create an array of even numbers

In [28]:
arr1d_step = np.arange(0, 10, 2)

The actual step is the third argument in np.arange(start, stop, step).

start = 0 → first element is 0

stop = 10 → stop before 10 (exclusive)

step = 2 → move 2 units each time

In [29]:
print(arr1d_step)

[0 2 4 6 8]


__`start`__

In [31]:
arr1d_start_5 = np.arange(5, 10)

In [32]:
print(arr1d_start_5)

[5 6 7 8 9]


__`double-precision floating-point numbers`__

In [34]:
arr1d_float = np.arange(10, dtype='float64')

In [35]:
print(arr1d_float)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


__step as a float, not an integer__

In [36]:
arr1d_float_step = np.arange(0, 3, 0.3)

start = 0 → first element

stop = 3 → exclusive, stops before 3

step = 0.3 → increment by 0.3 each time

In [37]:
print(arr1d_float_step)

[0.  0.3 0.6 0.9 1.2 1.5 1.8 2.1 2.4 2.7]


When arange() is used with floating-point arguments, it’s usually not possible to predict the number of elements obtained, due to the finite floating-point precision. For this reason, it’s better to use the NumPy linspace() function, which receives as an argument the number of elements desired instead of the step argument.

### __`reshape()`__
divides this linear array into different parts as specified by a shape argument.

In [39]:
arr3d = np.arange(16).reshape(2, 2, 4)

Shape (2, 2, 4) → three axes:
| Axis | Meaning                                      | Size |
| ---- | -------------------------------------------- | ---- |
| 0    | “blocks” or slices along the first dimension | 2    |
| 1    | rows inside each block                       | 2    |
| 2    | columns inside each row                      | 4    |


In [40]:
print(arr3d)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]


### __`linespace()`__

creates an ndarray of evenly spaced numbers within a defined interval.

The num argument determines how many elements will be in the array, and the function calculates the intervening numbers so that the intervals between them are the same.

In [42]:
np.linspace(start=0, stop=20, num=6)

array([ 0.,  4.,  8., 12., 16., 20.])

a 1D array of six floating-point values, with all the values evenly spaced. 

force the function to not include the endpoint by setting the Boolean parameter endpoint to False:

In [44]:
np.linspace(0, 20, 6, endpoint=False)

array([ 0.        ,  3.33333333,  6.66666667, 10.        , 13.33333333,
       16.66666667])

retrieve the size of the intervals between values, set the Boolean parameter retstep to True. 

In [45]:
arr1d, step = np.linspace(0, 20, 6, retstep=True)

In [49]:
print(arr1d)

[ 0.  4.  8. 12. 16. 20.]


In [50]:
step


np.float64(4.0)

By default, the linspace() function returns a dtype of float64. You can override this by passing it a dtype argument:

In [52]:
np.linspace(0, 20, 6, dtype='int64')

array([ 0,  4,  8, 12, 16, 20])

In [53]:
np.linspace(0, 20, 6).reshape(2, 3)

array([[ 0.,  4.,  8.],
       [12., 16., 20.]])

The linspace() function lets you control the number of elements in an array

https://realpython.com/np-linspace-numpy/

### __`Prefilled Arrays`__


create ndarrays using prefilled zeros, ones, random values, or values of your choosing.

__`zero()`__

create a zero-filled array, simply pass a shape tuple to the zero() function

In [55]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

__`ones()`__

In [58]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

__`np.eye()`__

In [59]:
np.eye(N=3, M=3, k=0)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

It creates a 2D array (matrix) with 1s on a diagonal and 0s everywhere else.

N=3

* Number of rows

M=3

* Number of columns

k=0

* Which diagonal gets the 1s

What does k mean?

Think of diagonals relative to the main diagonal:

| `k` value | Diagonal                    |
| --------- | --------------------------- |
| `0`       | Main diagonal               |
| `1`       | One above the main diagonal |
| `-1`      | One below the main diagonal |


In [48]:
np.eye(3, 3, k=1)


array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [49]:
np.eye(3, 3, k=-1)


array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

__`full()`__
fill an array with a custom value and data type

In [61]:
np.full((3, 3), fill_value=5, dtype='int64')

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

__`empty()`__

returns a new ndarray of a given shape filled with uninitialized arbitrary placeholder data of the given data type:

In [65]:
np.empty((2, 3, 2))

array([[[0.0e+000, 0.0e+000],
        [0.0e+000, 4.9e-324],
        [4.9e-324, 4.9e-324]],

       [[9.9e-324, 9.9e-324],
        [9.9e-324, 1.5e-323],
        [1.5e-323, 1.5e-323]]])

empty() does not initialize the values of the array like other creation functions, such as zeros(), and may therefore be marginally faster. However, the values stored in the newly allocated array are arbitrary. For reproducible behavior, you must set each element of the array before reading.



__`random()`__

For floating-point values between 0 and 1

In [68]:
np.random.random((3, 3))

array([[0.06483749, 0.9045905 , 0.44488024],
       [0.89918191, 0.88445717, 0.99112336],
       [0.03001565, 0.96710456, 0.45123608]])

https://numpy.org/doc/stable/reference/random/generator.html

## __`Array Attributes`__

ndarrays have attributes accessible through dot notation. 

![attributes chart](https://towardsdatascience.com/wp-content/uploads/2024/09/1AgvjsQZQEd5vxJrrqRM0DQ.png)

In [50]:
print(arr1d)

[1 2 3 4]


In [53]:
arr1dd = np.arange(0, 4)
print(arr1dd)

[0 1 2 3]


In [54]:
arr1dd.shape

(4,)

As a 1D array, there’s only one axis and thus only one index. Note the comma after the index, which tells Python that this is a tuple data type and not just an integer in parentheses.

In [72]:
arr1d.size

4

The size of the array is the total number of elements it contains. This is the same as the product of the elements returned by shape.

In [74]:
arr1d.dtype

dtype('int64')

In [75]:
test = np.array([5, 4, 9], dtype='int64')

In [76]:
test.dtype

dtype('int64')

To get the array’s strides, access the strides attribute with dot notation:

In [78]:
arr1d.strides

(8,)

When using strings in arrays, the dtype needs to include the length of the longest string. 

arr1d_str = np.array(['wheat', 'soybeans', 'corn'])

To see the data type and number of bits each item occupies, call the name attribute on dtype

In [84]:
arr1d_str.dtype.name

'str256'

In [85]:
arr1d_str.itemsize

32