In [2]:
import numpy as np

In [3]:
arr = np.array([[ 1, 2, 3], [ 4, 2, 5]])

__`ndarray.ndim`__: shows the number of axes (dimensions) of the array.

In [4]:
print("No. of dimensions: ", arr.ndim)

No. of dimensions:  2


__`ndarray.shape`__: It provides the size of the array for each dimension. The output data type is a tuple.

In [5]:
print("Shape of array: ", arr.shape)

Shape of array:  (2, 3)


__`ndarray.size`__ : It is the total number of elements in the array.

In [6]:
print("Size of array: ", arr.size)

Size of array:  6


__`ndarray.dtype`__: It shows the data type of the elements in the array.

In [7]:
print("Array stores elements of type: ", arr.dtype)

Array stores elements of type:  int64


__`ndarray.itemsize`__: It shows the length of one array element in bytes.

In [8]:
print("Length of one array element in bytes. : ", arr.itemsize)

Length of one array element in bytes. :  8


__`arr.itemsize`__ tells you how many bytes each individual element in the array occupies in memory.

| Data type | Bytes per element |
| --------- | ----------------- |
| `int32`   | 4 bytes           |
| `int64`   | 8 bytes           |
| `float32` | 4 bytes           |
| `float64` | 8 bytes           |


__`ndarray.data`__: It is an attribute offering direct access to the raw memory of a NumPy array.

In [9]:
print("array’s data. : ", arr.data)

array’s data. :  <memory at 0x10ec0fb90>


### __`reshape()`__

__`ndarray.reshape`__: It returns an array containing the same data with a new shape.

In [12]:
# Example: Converting a 1D Array to a 2D Array
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(4,3)
print (newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


### __`flatten()`__

__`ndarray.flatten`__: It returns a copy of the array flattened into a 1D array.

In [14]:
# Converting a multidimensional(3D) array into a 1D array
arr3D = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
flattened_array = arr3D.flatten()
flattened_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

### __`transpose()`__

__`ndarray.transpose`__: It swaps the rows and columns of a 2D array.

In [17]:
arr2D = np.array([[1, 2, 3], [4, 5, 6]])
# Transposing the 2D array
transposed_array = arr2D.transpose()
transposed_array

array([[1, 4],
       [2, 5],
       [3, 6]])