# Indexing

NumPy indexing lets you access an array element with an index value, starting from 0.

![indexing image](https://labcontent.simplicdn.net/data-content/content-assets/Data_and_AI/ADSP_Images/Lesson_03_NumPy/4_Indexing/Image_1.png)

In [2]:
# Creating 1D, 2D, and 3D NumPy arrays
import numpy as np
array_1d = np.array([1, 2, 3, 4, 5, 6])
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
array_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [5]:
print(array_1d)
print("_____")
print(array_2d)
print("_____")
print(array_3d)

[1 2 3 4 5 6]
_____
[[1 2 3]
 [4 5 6]]
_____
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


## `Access 1D NumPy Array Elements`

In [6]:
print(array_1d[3])

4


In [7]:
print(array_1d[1] + array_1d[0])

3


## `Access 2D NumPy Array Elements`

Consider a 2D array as a table, with dimensions representing rows and indexes representing columns.
![2D array access](https://labcontent.simplicdn.net/data-content/content-assets/Data_and_AI/ADSP_Images/Lesson_03_NumPy/4_Indexing/Image_2.png)

In [8]:
# Printing the third element in the first row of the 2D array
print('Third element in the first row: ', array_2d[0, 2])

Third element in the first row:  3


In [9]:
# Printing the second element in the second row of the 2D array
print('Second element in the second row: ', array_2d[1, 1])

Second element in the second row:  5


## `Access 3D NumPy Array Elements`
[x, y, z] corresponds to the xth element, yth row, and zth column.

In [10]:
print(array_3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [14]:
# Print the first element of the first row of the second 2D array within the 3D array
print(array_3d[1, 0, 0])
# The above code prints the value located in the first row and first column of the first matrix within the second set of matrices.

7


__Negative Indexing__

* Negative indices count backward from the end of the array.
* In a negative indexing system, the last element will be the first element with an index of -1, the second last element with an index of -2, and so on.

In [17]:
print(array_1d)

[1 2 3 4 5 6]


In [16]:
# Printing the fourth element from the end of the 1D array using negative indexing
print(array_1d[-3])

4


In [19]:
print(array_2d)

[[1 2 3]
 [4 5 6]]


In [18]:
# Printing the last element in the second row of the 2D array using negative indexing
print(array_2d[1, -1])

6


In [20]:
print(array_3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
# Printing the last element in the last row of the last 2D array within the 3D array using negative indexing
print(array_3d[1, 1, -1])

Problem Statement:
1. Create a one-dimensional NumPy array containing at least ten elements
2. Create a 2D NumPy array with a minimum of 3 rows and 4 columns
3. Create a 3D NumPy array with at least 2 matrices, each containing 2 rows and 3 columns
4. Access elements in NumPy arrays and utilize indexing and slicing techniques for efficient data retrieval
5. Access and print various elements from 1D, 2D, and 3D arrays using positive indexing
6. Perform and print some basic arithmetic operations (like addition or subtraction) using elements accessed from  1D, 2D, and 3D arrays
7. Access and print elements using negative indices in all three arrays

In [29]:
my_array_1d = np.array ([22, 44, 55, 77, 88, 99, 32, 54, 65, 76, 87, 98, 10, 45])
my_array_2d = np.array ([[222, 244, 255, 277,], [288, 299, 232, 274], [254, 265, 276, 287]])
my_array_3d = np.array ([[[322, 344, 355], [388, 399, 332]], [[354, 365, 376,], [398, 310, 365]]])

In [30]:
print(my_array_1d)

[22 44 55 77 88 99 32 54 65 76 87 98 10 45]


In [31]:
print(my_array_2d)

[[222 244 255 277]
 [288 299 232 274]
 [254 265 276 287]]


In [32]:
print(my_array_3d)

[[[322 344 355]
  [388 399 332]]

 [[354 365 376]
  [398 310 365]]]


In [33]:
print("No. of dimensions: ", my_array_1d.ndim)

No. of dimensions:  1


In [34]:
print("No. of dimensions: ", my_array_2d.ndim)

No. of dimensions:  2


In [35]:
print("No. of dimensions: ", my_array_3d.ndim)

No. of dimensions:  3


In [36]:
print("Shape of array: ", my_array_1d.shape)

Shape of array:  (14,)


In [37]:
print("Shape of array: ", my_array_2d.shape)

Shape of array:  (3, 4)


In [38]:
print("Shape of array: ", my_array_3d.shape)

Shape of array:  (2, 2, 3)


In [39]:
print("Size of array: ", my_array_1d.size)

Size of array:  14


In [40]:
print("Size of array: ", my_array_2d.size)

Size of array:  12


In [41]:
print("Size of array: ", my_array_3d.size)

Size of array:  12


In [42]:
print("Array stores elements of type: ", my_array_1d.dtype)

Array stores elements of type:  int64


In [43]:
print("Array stores elements of type: ", my_array_2d.dtype)

Array stores elements of type:  int64


In [44]:
print("Array stores elements of type: ", my_array_3d.dtype)

Array stores elements of type:  int64


In [45]:
print("Length of one array element in bytes. : ", my_array_1d.itemsize)

Length of one array element in bytes. :  8


In [46]:
print("Length of one array element in bytes. : ", my_array_2d.itemsize)

Length of one array element in bytes. :  8


In [47]:
print("Length of one array element in bytes. : ", my_array_3d.itemsize)

Length of one array element in bytes. :  8


In [48]:
print("array’s data. : ", my_array_1d.data)

array’s data. :  <memory at 0x110d113c0>


In [49]:
print("array’s data. : ", my_array_2d.data)

array’s data. :  <memory at 0x111a32b50>


In [50]:
print("array’s data. : ", my_array_3d.data)

array’s data. :  <memory at 0x111a414e0>


In [77]:
print(my_array_1d)
newarr_1 = my_array_1d.reshape(2,7)

[22 44 55 77 88 99 32 54 65 76 87 98 10 45]


In [78]:
print(newarr_1)

[[22 44 55 77 88 99 32]
 [54 65 76 87 98 10 45]]


In [53]:
print(my_array_2d)


[[222 244 255 277]
 [288 299 232 274]
 [254 265 276 287]]


In [56]:
my_array_2d = np.array ([[222, 244, 255, 277,], [288, 299, 232, 274], [254, 265, 276, 287]])
print(my_array_2d)
newarr_2 = my_array_2d.reshape(4,3)


[[222 244 255 277]
 [288 299 232 274]
 [254 265 276 287]]


In [57]:
print(newarr_2)

[[222 244 255]
 [277 288 299]
 [232 274 254]
 [265 276 287]]


In [58]:
print(my_array_3d)

[[[322 344 355]
  [388 399 332]]

 [[354 365 376]
  [398 310 365]]]


In [59]:
newarr_3 = my_array_2d.reshape(3,2,2)

In [74]:
print(newarr_3)

[[[222 244]
  [255 277]]

 [[288 299]
  [232 274]]

 [[254 265]
  [276 287]]]


In [61]:
flattened_array = newarr_3.flatten()

In [62]:
print(flattened_array)

[222 244 255 277 288 299 232 274 254 265 276 287]


In [73]:
print(my_array_2d)


[[222 244 255 277]
 [288 299 232 274]
 [254 265 276 287]]


In [64]:
transposed_array = my_array_2d.transpose()

In [65]:
print(transposed_array)

[[222 288 254]
 [244 299 265]
 [255 232 276]
 [277 274 287]]


In [72]:
print(my_array_1d)

[22 44 55 77 88 99 32 54 65 76 87 98 10 45]


In [80]:
print(my_array_2d)

[[222 244 255 277]
 [288 299 232 274]
 [254 265 276 287]]


In [81]:
print(my_array_3d)

[[[322 344 355]
  [388 399 332]]

 [[354 365 376]
  [398 310 365]]]


In [79]:
print(newarr_1)

[[22 44 55 77 88 99 32]
 [54 65 76 87 98 10 45]]


In [82]:
print(newarr_2)

[[222 244 255]
 [277 288 299]
 [232 274 254]
 [265 276 287]]


In [83]:
print(newarr_3)

[[[222 244]
  [255 277]]

 [[288 299]
  [232 274]]

 [[254 265]
  [276 287]]]


In [86]:
print(transposed_array)

[[222 288 254]
 [244 299 265]
 [255 232 276]
 [277 274 287]]


In [90]:

a = transposed_array
b = transposed_array
result = np.add (a,b)
print(result)

[[444 576 508]
 [488 598 530]
 [510 464 552]
 [554 548 574]]


In [94]:
print(my_array_1d)
y = my_array_1d
z = np.array([2, 4, 5, 7, 8, 9, 2, 4, 5, 6, 7, 8, 1, 5])
result = np.subtract (y,z)
print(result)

[22 44 55 77 88 99 32 54 65 76 87 98 10 45]
[20 40 50 70 80 90 30 50 60 70 80 90  9 40]


In [98]:
print(newarr_3)
print("___")
q = newarr_3
w = np.array([[[22, 24],[25, 27]],[[28, 29],[23, 24]],[[25, 65],[76, 87]]])
result = np.multiply (q,w)
print("result:",result)

[[[222 244]
  [255 277]]

 [[288 299]
  [232 274]]

 [[254 265]
  [276 287]]]
___
result: [[[ 4884  5856]
  [ 6375  7479]]

 [[ 8064  8671]
  [ 5336  6576]]

 [[ 6350 17225]
  [20976 24969]]]


In [100]:
print("flattened_array:", flattened_array)
t = flattened_array
p = np.array([2])
result = np.divide (t,p)
print(result)

flattened_array: [222 244 255 277 288 299 232 274 254 265 276 287]
[111.  122.  127.5 138.5 144.  149.5 116.  137.  127.  132.5 138.  143.5]


In [101]:
print("flattened_array:", flattened_array)
l = flattened_array
m = [2,2,2,2,2,2,5,5,5,5,5,5,]
n = np.power(l,m)
print(n)

flattened_array: [222 244 255 277 288 299 232 274 254 265 276 287]
[        49284         59536         65025         76729         82944
         89401  672109330432 1544375182624 1057227821024 1306860915625
 1601568101376 1947195170207]


In [103]:
print(my_array_3d)
np.median(my_array_3d)
print(np.median(my_array_3d))

[[[322 344 355]
  [388 399 332]]

 [[354 365 376]
  [398 310 365]]]
360.0


In [104]:
print(my_array_3d)
np.mean(my_array_3d)
print(np.mean(my_array_3d))

[[[322 344 355]
  [388 399 332]]

 [[354 365 376]
  [398 310 365]]]
359.0


In [105]:
print(my_array_3d)
np.std(my_array_3d)
print(np.std(my_array_3d))



[[[322 344 355]
  [388 399 332]]

 [[354 365 376]
  [398 310 365]]]
27.519689920733725


In [106]:
# Variance
np.var(my_array_3d)
print(np.var(my_array_3d))

757.3333333333334


In [107]:
array = np.array(my_array_3d)

np.percentile(my_array_3d,50)

np.float64(360.0)

In [109]:
x = np.array(['F','T','W'])
y = np.array(['Fuck', 'The', 'World'])
result = np.char.add(x,y)
print(result)

['FFuck' 'TThe' 'WWorld']


In [110]:
str = "Hello How Are You"
print(str)
z = np.char.replace (str, 'Hello', 'Hi')
print (z)

Hello How Are You
Hi How Are You


In [111]:
str = "Fuck the world"
print(str)
z = np.char.replace (str, 'world', 'planet')
print (z)

Fuck the world
Fuck the planet


In [113]:
# Converting all lowercase characters in a string to uppercase and vice-versa
str1 = "Fuck the world"
print(str1)
z = np.char.upper (str1)
print(z)
str2 = "FUCK MY LIFE"
print(str2)
s = np.char.lower (str2)
print(s)

Fuck the world
FUCK THE WORLD
FUCK MY LIFE
fuck my life


In [115]:
print(flattened_array)
print(flattened_array[1:7])

[222 244 255 277 288 299 232 274 254 265 276 287]
[244 255 277 288 299 232]


In [116]:
print(flattened_array)
print(flattened_array[0:6:2])

[222 244 255 277 288 299 232 274 254 265 276 287]
[222 255 288]


In [118]:
print(newarr_2)
print(newarr_2[0, 0:3])

[[222 244 255]
 [277 288 299]
 [232 274 254]
 [265 276 287]]
[222 244 255]


In [119]:
print(newarr_2)
print(newarr_2[0, 1:3])

[[222 244 255]
 [277 288 299]
 [232 274 254]
 [265 276 287]]
[244 255]


In [120]:
print(newarr_2)
print(newarr_2[0, 2:3])

[[222 244 255]
 [277 288 299]
 [232 274 254]
 [265 276 287]]
[255]


In [123]:
print(newarr_3)



[[[222 244]
  [255 277]]

 [[288 299]
  [232 274]]

 [[254 265]
  [276 287]]]


In [124]:
print(newarr_3[0,1:,1:])

[[277]]


In [125]:
print(newarr_3[1,0:,1:])

[[299]
 [274]]


In [126]:
# Negative slicing for 1D array

print(newarr_3[:-1])

[[[222 244]
  [255 277]]

 [[288 299]
  [232 274]]]


In [127]:
print(newarr_3[0, :-1])

[[222 244]]
