# Indexing

NumPy indexing lets you access an array element with an index value, starting from 0.

![indexing image](https://labcontent.simplicdn.net/data-content/content-assets/Data_and_AI/ADSP_Images/Lesson_03_NumPy/4_Indexing/Image_1.png)

In [2]:
# Creating 1D, 2D, and 3D NumPy arrays
import numpy as np
array_1d = np.array([1, 2, 3, 4, 5, 6])
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
array_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [5]:
print(array_1d)
print("_____")
print(array_2d)
print("_____")
print(array_3d)

[1 2 3 4 5 6]
_____
[[1 2 3]
 [4 5 6]]
_____
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


## `Access 1D NumPy Array Elements`

In [6]:
print(array_1d[3])

4


In [7]:
print(array_1d[1] + array_1d[0])

3


## `Access 2D NumPy Array Elements`

Consider a 2D array as a table, with dimensions representing rows and indexes representing columns.
![2D array access](https://labcontent.simplicdn.net/data-content/content-assets/Data_and_AI/ADSP_Images/Lesson_03_NumPy/4_Indexing/Image_2.png)

In [8]:
# Printing the third element in the first row of the 2D array
print('Third element in the first row: ', array_2d[0, 2])

Third element in the first row:  3


In [9]:
# Printing the second element in the second row of the 2D array
print('Second element in the second row: ', array_2d[1, 1])

Second element in the second row:  5


## `Access 3D NumPy Array Elements`
[x, y, z] corresponds to the xth element, yth row, and zth column.

In [10]:
print(array_3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [14]:
# Print the first element of the first row of the second 2D array within the 3D array
print(array_3d[1, 0, 0])
# The above code prints the value located in the first row and first column of the first matrix within the second set of matrices.

7


__Negative Indexing__

* Negative indices count backward from the end of the array.
* In a negative indexing system, the last element will be the first element with an index of -1, the second last element with an index of -2, and so on.

In [17]:
print(array_1d)

[1 2 3 4 5 6]


In [16]:
# Printing the fourth element from the end of the 1D array using negative indexing
print(array_1d[-3])

4


In [19]:
print(array_2d)

[[1 2 3]
 [4 5 6]]


In [18]:
# Printing the last element in the second row of the 2D array using negative indexing
print(array_2d[1, -1])

6


In [20]:
print(array_3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
# Printing the last element in the last row of the last 2D array within the 3D array using negative indexing
print(array_3d[1, 1, -1])

Problem Statement:
1. Create a one-dimensional NumPy array containing at least ten elements
2. Create a 2D NumPy array with a minimum of 3 rows and 4 columns
3. Create a 3D NumPy array with at least 2 matrices, each containing 2 rows and 3 columns
4. Access elements in NumPy arrays and utilize indexing and slicing techniques for efficient data retrieval
5. Access and print various elements from 1D, 2D, and 3D arrays using positive indexing
6. Perform and print some basic arithmetic operations (like addition or subtraction) using elements accessed from  1D, 2D, and 3D arrays
7. Access and print elements using negative indices in all three arrays