# Slicing

## __`Slicing 1D NumPy Arrays`__

In [1]:
import numpy as np
Employee_rating = np.array([1, 4, 3, 5, 6, 8, 9, 10, 12])
print(Employee_rating[1:7])

[4 3 5 6 8 9]


In [2]:
Books = np.array(['Physics','DataScience','Maths','Python','Hadoop', 'OPPs', 'Java', 'Cloud'])
print(Books[5:])

['OPPs' 'Java' 'Cloud']


## __`Slicing using step value`__

In [3]:
X = np.array([8, 7, 6, 5, 4, 3, 2, 1])
print(X[1:6:3])

[7 4]


```python
X = np.array([8, 7, 6, 5, 4, 3, 2, 1])
```
Indexes:

```python
Index:  0  1  2  3  4  5  6  7
Value:  8  7  6  5  4  3  2  1
```

The slice: `X[1:6:3]`

```python
The slice: X[1:6:3]
```

1️⃣ Start = 1

Begin at index 1 (value 7)

2️⃣ Stop = 6

Stop before index 6 (index 6 is excluded)

```python
1, 2, 3, 4, 5
```

3️⃣ Step = 3

Take every 3rd element starting from index 1

```python
1 → 4
```

Values returned

* Index 1 → 7

* Index 4 → 4

```python
[7 4]
```

## __`Slicing 2D Arrays`__

In [6]:
Z = np.array([[11, 22, 33, 44, 55], [66, 77, 88, 99, 110]])
print(Z[0, 2:3])

[33]


## __`Slicing 3D Arrays`__

In [7]:
array_3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(array_3d[0,1:,1:])

[[5 6]]


__print(array_3d[0,1:,1:])__

array_3d[0, 1:, 1:] selects the first block, then the last row, then the last two columns.

1️⃣ First dimension: 0
Select the first block:

```python
[[1, 2, 3],
 [4, 5, 6]]
```

2️⃣ Second dimension: 1:
Select rows starting from index 1 to the end:

```python
[[4, 5, 6]]
```

3️⃣ Third dimension: 1:
Select columns starting from index 1 to the end:

```python
[5, 6]

```


## __`Negative Slicing`__

In [8]:
# Negative slicing for 1D array
Neg_slice = np.array([13, 34, 58, 69, 44, 56, 37,24])
print(Neg_slice[:-1])

[13 34 58 69 44 56 37]
